spring.application.name=ms-auth
spring.data.mongodb.uri=${MONGODB_URI:mongodb://admin:admin@localhost:27017/bantads_auth?authSource=admin}
spring.data.mongodb.auto-index-creation=true
server.port=${SERVER_PORT:8082}
management.endpoints.web.exposure.include=health,info
